Support persisted queries for POST requests
warrenday/graphql-network-inspector pull request #93
Opened 2023-03-13 21:03 UTC by PhilippeChab

## Description

Thanks to this [commit](https://github.com/warrenday/graphql-network-inspector/commit/f87a6312dc7b40d9a58cee687f38432a673927a9), the extension now supports GET persisted queries.  While GET requests allow the browser to use HTTP caching, persisted queries can also be made with POST requests.

This PR adds the support to persisted queries made with POST requests.

## Screenshot

- The color can be changed. 
- The new 'unknown' type is because a persisted query made as a POST can be either a query or a mutation.

![CleanShot 2023-03-13 at 16 53 49@2x](https://user-images.githubusercontent.com/26422481/224829981-5d98035c-e8fb-4e10-a4a4-12fe0b849a0f.png)

## Checklist

- [ ] Unit/Integration tests added
- [ ] POST persisted queries are now supported

2023-03-13 22:49 UTC, Odonno commented
Oh, good catch. Indeed, we can detect persisted queries for POST requests, although this is not the primary use case.

However, I am not really a fan of this "unknown" thing. You're right in the sense that we don't know what kind of operation we're doing, but persisted query is mainly for queries. Queries do not change often, but mutations do. That's why mutations are not good candidates for persisted queries. I would vote to assume that a persisted query (GET or POST) should be treated as a query.

2023-03-14 00:26 UTC, PhilippeChab commented
> ... but persisted query is mainly for queries. Queries do not change often, but mutations do. That's why mutations are not good candidates for persisted queries.

This is not true. :) Persisted queries are equally as useful for queries as for mutations. The goal of a persisted query is purely to reduce the request's size, whether it is a POST or a GET doesn't matter.

Executing a GraphQL request as a GET is an other optimization to exploit HTTP caching, something that cannot be done when performing a POST.

That being said, I agree that `Unknowns` is not ideal UX wise. `Persisted POSTs`, maybe? I'm open to any suggestion. :)

2023-03-14 15:46 UTC, PhilippeChab commented
Let's go with `persisted!`

2023-03-14 17:10 UTC, Odonno requested changes

2023-03-14 17:10 UTC, Odonno commented on src/helpers/graphqlHelpers.ts
GET persisted query should also return "persisted", right?

2023-03-14 17:10 UTC, Odonno commented on src/helpers/graphqlHelpers.ts
> +    } else {
Maybe we can try an early return instead of a `else` here.

2023-03-14 20:50 UTC, PhilippeChab commented on src/helpers/graphqlHelpers.ts
Yeah, I wasn't sure about that one since we know for sure that GETs are queries, but I suppose it makes sense to categorize them as `persisted` as well.

I'll make the change.

2023-03-15 08:07 UTC, Odonno commented
Looks good to me.

2023-03-22 09:18 UTC, warrenday commented
Looks great! Thanks @PhilippeChab

2023-03-22 09:18 UTC, merged